rvm:
  - 2.2
  - 2.3.1
gemfile:
  - gemfiles/rails4.gemfile
  - gemfiles/rails5.gemfile
before_install:
  - gem update bundler
notifications:
  email:
    recipients:
      - test-unit-commit@googlegroups.com
